import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Header from "@/component/header/Header";
import Head from "next/head";
import Footer from "@/component/footer/Footer";
//import { headers } from 'next/headers';
//import { notFound } from "next/navigation";
//import { ContextProviderNext, ctxTransfer } from "@/context/Context";
import {NextIntlClientProvider} from 'next-intl';
import {getLocale, getMessages} from 'next-intl/server';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const locale = await getLocale();
 
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html  lang={locale}> 
      <Head >
         <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body className={inter.className} suppressHydrationWarning={true}>
      <Header />
      <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      <Footer />
        </body> 
    </html>
  );
}
