import Footer from "@/component/footer/Footer";
import Header from "@/component/header/Header";
import type { Metadata } from "next";
//import { Inter } from "next/font/google";
//import "@/app/globals.css";
//import Head from "next/head";
//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Ludo Page",
  description: "Generated by ludo app",
};

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
      <>
      <Header />
        {children}
      <Footer />
      </>
  ); 
}
